version: '3.8'

services:
  openbank-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_APP_NAME=OpenBank
      - NEXT_PUBLIC_APP_VERSION=1.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Base de données pour les données utilisateur (optionnel)
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: openbank
  #     POSTGRES_USER: openbank_user
  #     POSTGRES_PASSWORD: openbank_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped

  # Redis pour le cache et les sessions (optionnel)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped

volumes:
  postgres_data: 